apiVersion: batch/v1
kind: CronJob
metadata:
  name: reporting-cron-job
spec:
  schedule: "* * * * *"   # cron expression
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 25
      activeDeadlineSeconds: 20 # if the task isn't completed in 20 secs, the job will fail and pods will be terminated
      template:
        spec:
          containers:
          - name: reporting-tool
            image: reporting-tool
          restartPolicy: OnFailure
