apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3    # it will create 3 pods to run this job (created sequentially by default)
  parallelism: 3    # it will run the job parallely in 3 pods
  template:
    spec:
      containers:
      - name: math-add
        image: ubuntu
        command: ["expr",  "3", "+", "2"]
      restartPolicy: Never
