apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp
spec:
  serviceAccountName: build-robot # assign this service account to this pod
  containers:
  - name: nginx-container
    image: nginx
    command: ["sleep"] # equivalent to ENTRYPOINT in docker
    args: ["5000"] # equivalent to CMD in docker
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 500Mi
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: blue
      - name: APP_MODE
        valueFrom:
          configMapKeyRef:
            name: myapp-config
            key: APP_MODE
    envFrom:
      - configMapRef:
          name: myapp-config
      - secretRef:
          name: myapp-secret
