apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: blue
      - name: APP_MODE
        valueFrom:
          configMapKeyRef:
            name: myapp-config
            key: APP_MODE
    envFrom:
      - configMapRef:
          name: myapp-config
