apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce   # ReadWriteOnce | ReadWriteMany | ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle    # how the PV should react if the PVC is deleted
  storageClassName: slow
  # hostPath:
  #   path: /tmp
  awsElasticBlockStore:
    volumeID: <volume-ID>
    fsType: ext4
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
