apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
# A PV will get mapped to this PVC if the request criterias are met eg: storage, accessModes etc
# other it will remain pending until a matching PV is available
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
